springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha

spring:
  application:
    name: jwt_test_backend
  security:
    jwt:
      # JWT ??
      privateKey: askjdfhaiusdfhai124532
      # ????????
      expire: 30
  datasource:
    dynamic:
      #  dynamic????
      primary: mysql  #??????????????,?????master
      strict: false  #??????,??false???. ????????????????????,???????????.
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test
          username: root
          password: MySQL#Li2024
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  web:
    # ???????????????
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30


# ?????????
email:
  user: 836046238@qq.com
  code: hxryowtcmsadbddh
  host: smtp.qq.com
  auth: true