spring:
  application:
    name: jwt_test_backend
  security:
    jwt:
      privateKey: askjdfhaiusdfhai124532
      expire: 30
  datasource:
    dynamic:
      #  dynamic????
      primary: mysql  #??????????????,?????master
      strict: false  #??????,??false???. ????????????????????,???????????.
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test
          username: root
          password: MySQL#Li2024